package practiceproblems.classChallenges



/*You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
Example 1:

  Input: s = "abcd", t = "abcde"
  Output: "e"
  Explanation: 'e' is the letter that was added.
  Example 2:

  Input: s = "", t = "y"
  Output: "y"

  Constraints:
  0 <= s.length <= 1000
  t.length == s.length + 1
  s and t consist of lowercase English letters.*/



//work on this put on hold for now, will use a pattern match as scala doesnt want me to declare a variable in an if statement
/*object oneExtraLetter extends App {
  println("input a string: ")
  var string1: String = scala.io.StdIn.readLine()
  println("input another: ")
  var string2: String = scala.io.StdIn.readLine()

  if(string1.length >= string2.length){
    var longer = string1
    var shorter = string2
  }else{
    var longer = string2
    var shorter = string1
  }
  println(longer)
  /*for (i <- 0 until longer.length){

  }*/

}*/
